# Generated by Django 5.2.1 on 2026-04-03 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gas_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('smoke_level', models.FloatField()),
                ('prediction_label', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sensor_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
