# Generated by Django 5.2.12 on 2026-04-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="history",
            table="user_history",
        ),
    ]
