name: CI Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      # Run Django checks
      - name: Django check
        working-directory: backend
        run: python manage.py check